config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'home#index'
  resources :categories, except: [:show]
  resources :clients, except: [:show]
  resources :suppliers, except: [:show]
  resources :products, except: [:show]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :products 
end

app/models/client.rb
class Client < ApplicationRecord
    has_many :sales
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :categories
  belongs_to :suppliers
  has_many :warehouse_records
end

app/models/sale.rb
class Sale < ApplicationRecord
    belongs_to :client
end

app/models/supplier.rb
class Supplier < ApplicationRecord
    has_many :products
    has_many :warehouse_records
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/warehouse_record.rb
class WarehouseRecord < ApplicationRecord
  belongs_to :supplier
  belongs_to :product
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
    layout :layout_by_resource
  
    private
  
    def layout_by_resource
      if devise_controller?
        "devise"
      else
        "application"
      end
    end
  
  
  end
  

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:edit, :update, :destroy]

  def index
    @categorias = Category.all
  end

  def new
    @categoria = Category.new
  end

  def edit
  end

  def create
    @categoria = Category.new(category_params)

    respond_to do |format|
      if @categoria.save
        format.json { head :no_content }
        format.js
      else
        format.json { render json: @categoria.errors.full_messages, status: :unprocessable_entity }
        format.js { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @categoria.update(category_params)
        format.json { head :no_content }
        format.js
      else
        format.json { render json: @categoria.errors.full_messages, status: :unprocessable_entity }
        format.js { render :edit }
      end
    end
  end

  def destroy
    @categoria.destroy
    respond_to do |format|
      format.json { head :no_content }
      format.js
    end
  end

  private 
    def set_category
      @categoria = Category.find(params[:id])
    end

    def category_params
      params.require(:category).permit(:nombre, :descripcion)
    end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:edit, :update, :destroy]

  def index
      @clientes = Client.all
  end

  def new 
      @cliente = Client.new
  end

  def create 
      @cliente = Client.new(client_params)

      respond_to do |format|
          if @cliente.save
              format.json { head :no_content }
              format.js
            else
              format.json { render json: @cliente.errors.full_messages, status: :unprocessable_entity }
              format.js { render :new }
            end
      end
  end

  def edit
  end

  def update
      respond_to do |format|
          if @cliente.update(client_params)
              format.json {head :no_content}
              format.js
          else
              format.json { render json: @cliente.error.full_messages, status: :unprocessable_entity }
              format.js { render :edit }
          end
      end
  end

  def destroy
      @cliente.destroy
      respond_to do |format|
          format.js
          format.json { head :no_content }
      end
  end

  def buscador
    @resultados = Client.buscador(params[:termino]).map do |cliente|
      {
          id: cliente.id,
          nombre_cliente: cliente.nombre
      }
    end

    respond_to do |format|
      format.json { render :json => @resultados }
    end
  end

  private 
  def set_client
      @cliente = Client.find(params[:id])
  end

  def client_params
      params.require(:client).permit(:nombre, :direccion, :telefono)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    before_action :set_product, only: [:edit, :update, :destroy, :show]
    before_action :set_categories, only: [:new, :edit, :create]
    before_action :set_suppliers, only: [:new, :edit, :create]
  
    def index
      @productos = Product.all
    end
  
    def show 
    end
  
    def new
      @product = Product.new
    end
  
    def edit
    end
  
    def create
      @product = Product.new(product_params)
      respond_to do |format|
        if @product.save
          format.json {head :no_content}
          format.js
        else
          debugger
          format.json { render json: @product.errors.full_messages, status: :unprocessable_entity }
          format.js { render :new }
        end
      end
    end
  
    def update
      respond_to do |format|
        if @product.update(product_params)
          format.json { head :no_content }
          format.js
        else
          format.json { render json: @product.errors.full_messages, status: :unprocessable_entity }
          format.js { render :edit }
        end
      end
    end
  
    def destroy
      @product.destroy
      respond_to do |format|
        format.json { head :no_content }
        format.js
      end
    end
  
    def buscador
      @resultados = Product.buscador(params[:termino]).map do |producto|
        {
          id: producto.id,
          nombre_producto: producto.nombre,
          existencia: producto.existencia
        }
      end
  
      respond_to do |format|
        format.json { render :json => @resultados }
      end
    end
  
    private
    def product_params
      params.require(:product).permit(:imagen, :nombre, :descripcion, :existencia, :precio, :category_id, :supplier_id)
    end
  
    def set_product
      @product = Product.find(params[:id])
    end
  
    def set_categories
      @categorias = Category.all
    end
  
    def set_suppliers
      @proveedores = Supplier.all
    end
  end

app/controllers/suppliers_controller.rb
class SuppliersController < ApplicationController
    before_action :set_supplier, only: [:edit, :update, :destroy]
  
    def index
      @proveedores = Supplier.all
    end
  
    def new
      @proveedor = Supplier.new
    end
  
    def edit
    end
  
    def create
      @proveedor = Supplier.new(supplier_params)
      
      respond_to do |format|
        if @proveedor.save
          format.json { head :no_content }
          format.js
        else
          format.json { render json: @proveedor.errors.full_messages, status: :unprocessable_entity }
          format.js { render :new }
        end
      end
    end
  
    def update
      respond_to do |format|
        if @proveedor.update(supplier_params)
          format.json { head :no_content }
          format.js
        else
          format.json { render json: @proveedor.errors.full_messages, status: :unprocessable_entity }
          format.js { render :edit }
        end
      end
    end
  
    def destroy
      @proveedor.destroy
      respond_to do |format|
        format.json { head :no_content }
        format.js
      end
    end
  
    def buscador
      @resultados = Supplier.buscador(params[:termino]).map do |proveedor|
        {
            id: proveedor.id,
            nombre_proveedor: proveedor.nombre
        }
      end
  
      respond_to do |format|
        format.json { render :json => @resultados }
      end
    end
  
    private
  
    def set_supplier
      @proveedor = Supplier.find(params[:id])
    end
  
    def supplier_params
      params.require(:supplier).permit(:nombre, :direccion, :telefono)
    end
  
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/application/_buscador_cliente.html.erb
<div class="modal fade" id="buscador_cliente" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="modal-items-title">Buscador de clientes</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body-items modal-body" id="modal-body-items">
        <div class="form-group">
            <label for="buscador">Ingresa el nombre del cliente</label>
            <input type="text" class="form-control" data-venta = "<%= @venta.id %>" id="buscador_clientes" placeholder="Nombre cliente...">
        </div>
        <table class="table table-dark" id="tabla_buscador_clientes" >
            <thead>
            <tr>
            <th >Nombre</th>
            <th >Agregar</th>
            </tr>
            </thead>
            <tbody>
                
            </tbody>
        </table>
      </div>
      <div class="modal-footer" id="modal-footer-items">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
      </div>
    </div>
  </div>
</div>

app/views/application/_buscador_producto.html.erb
<div class="modal fade" id="buscador_producto" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="modal-items-title">Buscador de productos</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body-items modal-body" id="modal-body-items">
        <div class="form-group">
            <label for="buscador">Ingresa el nombre del producto</label>
            <input type="text" class="form-control" data-tipo = "<%= @tipo %>" data-model = "<%= @model.try(:id) %>" id="buscador_productos" placeholder="Nombre producto...">
        </div>
        <div class="form-group">
            <label for="buscador">Ingresa una cantidad</label>
            <input type="number" class="form-control" id="cantidad_producto" placeholder="Ingresa la cantidad a vender..." value="1">
        </div>
        <table class="table table-dark" id="tabla_buscador" >
            <thead>
                <tr>
                <th >Nombre</th>
                <th >Existencia</th>
                <th >Agregar</th>
                </tr>
            </thead>
            <tbody>
                
            </tbody>
        </table>
      </div>
      <div class="modal-footer" id="modal-footer-items">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
      </div>
    </div>
  </div>
</div>

app/views/application/_buscador_proveedor.html.erb
<div class="modal fade" id="buscador_proveedor" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="modal-items-title">Buscador de proveedores</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body-items modal-body" id="modal-body-items">
        <div class="form-group">
            <label for="buscador">Ingresa el nombre del proveedor</label>
            <input type="text" class="form-control" data-warehouse = "<%= @entrada_almacen.id %>" id="buscador_proveedores" placeholder="Nombre proveedor...">
        </div>
        <table class="table table-dark" id="tabla_buscador_proveedores" >
            <thead>
            <tr>
            <th >Nombre</th>
            <th >Agregar</th>
            </tr>
            </thead>
            <tbody>
                
            </tbody>
        </table>
      </div>
      <div class="modal-footer" id="modal-footer-items">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
      </div>
    </div>
  </div>
</div>

app/views/categories/_form.html.erb
<%= form_for @categoria, remote: true do |f| %>
    <div class="form-group">
      <h4 class="control-label">Datos de la categoría:</h4>
    </div>

    <div class="item form-group<%= @categoria.errors[:nombre].any? ? ' has-error has-feedback' : '' %>">
      <%= f.label :nombre, "Nombre de Categoría: " %>
      <div class="input-group">
        <%= f.text_field :nombre, {:class=> "form-control", :placeholder=>"Introduzca el nombre de la categoría..."} %>        
        <%if @categoria.errors[:nombre].any? %>
          <p class="bg-danger"><%= @categoria.errors[:nombre].to_s[/\w([^"]*)/] %></p>
        <% end %>
      </div>
    </div>

    <div class="item form-group<%= @categoria.errors[:descripcion].any? ? ' has-error has-feedback' : '' %>">
      <%= f.label :descripcion, "Descripción de la categoría: " %>
      <div class="input-group">
        <%= f.text_area :descripcion, {class: "form-control", :placeholder=>"Introduzca la descripción de la categoría..."} %>
        <%if @categoria.errors[:descripcion].any? %>
          <p class="bg-danger"><%= @categoria.errors[:descripcion].to_s[/\w([^"]*)/] %></p>
        <% end %>
      </div>
    </div>

    <div class="actions col-md-9 col-sm-9 col-xs-12 col-md-offset-3">
      <%= f.submit @categoria.new_record? ? "Crear Categoría" : "Actualizar Categoría", :class => "btn btn-success"%>
    </div>  
<% end %>

app/views/categories/create.js.erb
$('#modalCategorias').modal('toggle');
$('#tablaCategorias').append(
    '<tr id="categoria_<%= @categoria.id %>" ><td><%= @categoria.nombre %></td><td><%= @categoria.descripcion %></td><td><%= link_to 'editar', edit_category_path(@categoria), html_options = {class: "btn btn-info btn-xs", remote: true} %> <%= link_to "Borrar", @categoria, remote: true, method: :delete, data: { confirm: "¿Borrar categoria: #{@categoria.nombre}?"}, class: "btn btn-danger btn-xs" %></td></tr>'
);

app/views/categories/destroy.js.erb
$('#categoria_<%= @categoria.id %>').fadeOut();

app/views/categories/index.html.erb
<h1 class="h3 mb-2 text-gray-800">Categorias de productos</h1>

<div>  
  <%= link_to new_category_path, {remote: true, class: "btn btn-info", id: "anadir-categoria-btn"}  do %>
    <span class="fas fa-plus-square" ></span>
  <% end %>
</div>
<br />

<div class="card shadow mb-4">
  <div class="card-body">
    <div class="table-responsive">
       <table id="tablaCategorias" class="table table-bordered" width="100%">
         <thead>
           <tr>
             <th>Nombre Categoría</th>
             <th>Descripcion</th>
             <th></th>
           </tr>
         </thead>
         <tbody>
         <% @categorias.each do |cat| %>
            <tr id="categoria_<%= cat.id %>" >
                <td><%= cat.nombre %></td>
                <td><%= cat.descripcion %></td>
                <td>
                <%= link_to "editar", edit_category_path(cat), html_options = {class: "btn btn-info btn-xs", remote: true} %>
                <%= link_to 'Borrar', cat, remote: true, method: :delete, data: { confirm: "¿Borrar categoria: #{cat.nombre}?"}, class: "btn btn-danger btn-xs" %>
                </td>
            </tr>
         <% end %>
         </tbody>
       </table>
    </div>
  </div>
</div>

<%= render 'modal_categorias' %>

app/views/categories/update.js.erb
$('#modalCategorias').modal('toggle');
$('#categoria_<%= @categoria.id %>').replaceWith(
    '<tr id="categoria_<%= @categoria.id %>" ><td><%= @categoria.nombre %></td><td><%= @categoria.descripcion %></td><td><%= link_to 'editar', edit_category_path(@categoria), html_options = {class: "btn btn-info btn-xs", remote: true} %> <%= link_to "Borrar", @categoria, remote: true, method: :delete, data: { confirm: "¿Borrar categoria: #{@categoria.nombre}?"}, class: "btn btn-danger btn-xs" %></td></tr>'
);

app/views/clients/create.js.erb
$('#modalClientes').modal('toggle');
$('#tablaClientes').append(
    '<tr id="cliente_<%= @cliente.id %>" ><td><%= @cliente.nombre %></td><td><%= @cliente.direccion %></td><td><%= @cliente.telefono %></td><td><%= link_to 'editar', edit_client_path(@cliente), html_options = {class: "btn btn-info btn-xs", remote: true} %> <%= link_to "Borrar", @cliente, remote: true, method: :delete, data: { confirm: "¿Borrar cliente: #{@cliente.nombre}?"}, class: "btn btn-danger btn-xs" %></td></tr>'
);

app/views/clients/destroy.js.erb
$('#cliente_<%= @cliente.id %>').fadeOut();

app/views/clients/index.html.erb
<!-- Page Heading -->
<h1 class="h3 mb-2 text-gray-800">Clientes</h1>
<!-- DataTales Example -->
<div>  
  <%= link_to new_client_path, {remote: true, class: "btn btn-info", id: "anadir-cliente-btn"}  do %>
    <span class="fas fa-plus-square" style=""></span>
  <% end %>
</div>
<br />
<div class="card shadow mb-4">
<div class="card-body">
    <div class="table-responsive">
    <table class="table table-bordered" id="tablaClientes" width="100%" cellspacing="0">
        <thead>
        <tr>
            <th>Nombre</th>
            <th>Dirección</th>
            <th>Teléfono</th>
            <th>Acciones</th>
        </tr>
        </thead>
        <tbody>
            <% @clientes.each do |clie| %>
            <tr id="cliente_<%= clie.id %>" >
                <td><%= clie.nombre %></td>
                <td><%= clie.direccion %></td>
                <td><%= clie.telefono %></td>
                <td>
                <%= link_to "editar", edit_client_path(clie), html_options = {class: "btn btn-info btn-xs", remote: true} %>
                <%= link_to "Borrar", clie, remote: true, method: :delete, data: { confirm: "¿Borrar cliente: #{clie.nombre}?"}, class: "btn btn-danger btn-xs" %>
                </td>
            </tr>
            <% end %>
        </tbody>
    </table>
    </div>
  </div>
</div>
<%= render 'modal_clientes' %>

app/views/clients/update.js.erb
$('#modalClientes').modal('toggle');
$('#cliente_<%= @cliente.id %>').replaceWith(
    '<tr id="cliente_<%= @cliente.id %>" ><td><%= @cliente.nombre %></td><td><%= @cliente.direccion %></td><td><%= @cliente.telefono %></td><td><%= link_to 'editar', edit_client_path(@cliente), html_options = {class: "btn btn-info btn-xs", remote: true} %> <%= link_to "Borrar", @cliente, remote: true, method: :delete, data: { confirm: "¿Borrar cliente: #{@cliente.nombre}?"}, class: "btn btn-danger btn-xs" %></td></tr>'
);

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Ecommerce</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
 
    <%= stylesheet_link_tag "sb-admin-2.min" %>
  </head>
  <body id="page-top">
    <div id="wrapper">
      <!-- Sidebar -->
      <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

        <!-- Sidebar - Brand -->
        <%= link_to root_path, class: "sidebar-brand d-flex align-items-center justify-content-center"  do %>
          <div class="sidebar-brand-text mx-3"> Ecommerce Tecnologico </div>
        <%end%>

        <!-- Divider -->
        <hr class="sidebar-divider my-0">

        <!-- Nav Item - Dashboard -->

        <!-- Divider -->
        <hr class="sidebar-divider">

        <div class="sidebar-heading">
          Módulos
        </div>

        <li class="nav-item">
          <%= link_to categories_path, class: "nav-link"  do %>
            <i class="fas fa-fw fa-tags"></i>
            <span>Categorías</span>
          <%end%>
        </li>

                <li class="nav-item">
          <%= link_to products_path, class: "nav-link"  do %>
            <i class="fas fa-fw fa-shopping-basket"></i>
            <span>Productos</span>
          <%end%>
        </li>




        <li class="nav-item">
          <%= link_to clients_path, class: "nav-link"  do %>
            <i class="fas fa-fw fa-users"></i>
            <span>Clientes</span></a>
          <%end%>
        </li>

        <li class="nav-item">
          <%= link_to suppliers_path, class: "nav-link"  do %>
            <i class="fas fa-fw fa-truck"></i>
            <span>Proveedores</span>
          <%end%>
        </li>



      </ul>
      <!-- End of Sidebar -->
      <div id="content-wrapper" class="d-flex flex-column">
        <div id="content">
          <!-- Topbar -->
          <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

            <!-- Sidebar Toggle (Topbar) -->
            <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
              <i class="fa fa-bars"></i>
            </button>

            <!-- Topbar Search -->
            <%= form_tag( '/search', options = { class: "d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search" }) do %>
              <div class="input-group">
                <%= text_field_tag("termino", value = nil, options = { class: "form-control bg-light border-0 small", placeholder: "Search for..."}) %>
                <div class="input-group-append">
                  <%= submit_tag(value = "Buscar", options = { class: "btn btn-primary" }) do %>
                    <i class="fas fa-search fa-sm"></i>
                  <% end %>
                </div>
              </div>
            <% end %>

            <!-- Topbar Navbar -->
            <ul class="navbar-nav ml-auto">

              <!-- Nav Item - Search Dropdown (Visible Only XS) -->
              <li class="nav-item dropdown no-arrow d-sm-none">
                <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <i class="fas fa-search fa-fw"></i>
                </a>
                <!-- Dropdown - Messages -->
                <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in" aria-labelledby="searchDropdown">
                  <form class="form-inline mr-auto w-100 navbar-search">
                    <div class="input-group">
                      <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
                      <div class="input-group-append">
                        <button class="btn btn-primary" type="button">
                          <i class="fas fa-search fa-sm"></i>
                        </button>
                      </div>
                    </div>
                  </form>
                </div>
              </li>

              <div class="topbar-divider d-none d-sm-block"></div>

              <!-- Nav Item - User Information -->


            </ul>

          </nav>
          <!-- End of Topbar -->
          <div class="container-fluid">
            <%= yield %>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/products/index.html.erb
<h1 class="h3 mb-2 text-gray-800">Productos</h1>
<div>  
  <%= link_to new_product_path, { remote: true, class: "btn btn-info" }  do %>
    <span class="fas fa-plus-square" ></span>
  <% end %>
</div>
<br />
<div class="card shadow mb-4">
<div class="card-body">
    <div class="table-responsive">
    <table class="table table-bordered" id="tablaProductos" width="100%" cellspacing="0">
        <thead>
        <tr>
            <th></th>
            <th>Nombre producto</th>
            <th>Existencia</th>
            <th>Precio</th>
            <th>Categoria</th>
            <th>Proveedor</th>
        </tr>
        </thead>
        <tbody>
            <% @productos.each do |prod| %>
            <tr id="producto_<%= prod.id %>" >
                <td><%= image_tag(prod.imagen.url, size: "50x50", class: "rounded-circle") if prod.imagen? %></td>
                <td><%= prod.nombre %></td>
                <td><%= prod.existencia %></td>
                <td>$<%= prod.precio %></td>
                <td><%= prod.category != nil ? prod.category.nombre : "No tiene categoria" %></td>
                <td><%= prod.supplier != nil ? prod.supplier.nombre : "No tiene proveedor" %></td>
                <td>
                <%= link_to "editar", edit_product_path(prod), html_options = {class: "btn btn-info btn-xs", remote: true} %>
                <%= link_to "Borrar", prod, remote: true, method: :delete, data: { confirm: "¿Borrar producto: #{prod.nombre}?"}, class: "btn btn-danger btn-xs" %>
                </td>
            </tr>
            <% end %>
        </tbody>
    </table>
    </div>
  </div>
</div>
<%= render 'modal_productos' %>

app/views/products/update.js.erb
$('#modalProductos').modal('toggle');
$('#producto_<%= @product.id %>').replaceWith(
    '<tr id="producto_<%= @product.id %>" ><td><%= image_tag(@product.imagen.url, size: "50x50", class: "rounded-circle") if @product.imagen? %></td><td><%= @product.nombre %></td><td><%= @product.existencia %></td><<td>$ <%= @product.precio %></td><td><%= @product.category != nil ? @product.category.nombre : "No tiene categoria" %></td><td><%= @product.supplier != nil ? @product.supplier.nombre : "No tiene proveedor" %></td><td><%= link_to 'editar', edit_product_path(@product), html_options = {class: "btn btn-info btn-xs", remote: true} %> <%= link_to "Borrar", @product, remote: true, method: :delete, data: { confirm: "¿Borrar producto: #{@product.nombre}?"}, class: "btn btn-danger btn-xs" %></td></tr>'
);

app/views/suppliers/create.js.erb
$('#modalProveedores').modal('toggle');
$('#tablaProveedores').append(
    '<tr id="proveedor_<%= @proveedor.id %>" ><td><%= @proveedor.nombre %></td><td><%= @proveedor.direccion %></td><td><%= @proveedor.telefono %></td><td><%= link_to 'editar', edit_supplier_path(@proveedor), html_options = {class: "btn btn-info btn-xs", remote: true} %> <%= link_to "Borrar", @proveedor, remote: true, method: :delete, data: { confirm: "¿Borrar categoria: #{@proveedor.nombre}?"}, class: "btn btn-danger btn-xs" %></td></tr>'
);

app/views/suppliers/index.html.erb
<!-- Page Heading -->
<h1 class="h3 mb-2 text-gray-800">Proveedores</h1>
<div>  
  <%= link_to new_supplier_path, {remote: true, class: "btn btn-info", id: "anadir-proveedor-btn"}  do %>
    <span class="fas fa-plus-square" style=""></span>
  <%end%>
</div>
<br />
<div class="card shadow mb-4">
<div class="card-body">
    <div class="table-responsive">
    <table class="table table-bordered" id="tablaProveedores" width="100%" cellspacing="0">
        <thead>
        <tr>
            <th>Nombre</th>
            <th>Dirección</th>
            <th>Teléfono</th>
        </tr>
        </thead>
        <tbody>
        <% @proveedores.each do |prov| %>
        <tr id="proveedor_<%= prov.id %>" >
            <td><%= prov.nombre %></td>
            <td><%= prov.direccion %></td>
            <td><%= prov.telefono %></td>
            <td>
            <%= link_to "editar", edit_supplier_path(prov), html_options = {class: "btn btn-info btn-xs", remote: true} %>
            <%= link_to 'Borrar', prov, remote: true, method: :delete, data: { confirm: "¿Borrar proveedor: #{prov.nombre}?"}, class: "btn btn-danger btn-xs" %>
            </td>
        </tr>
        <% end %>
        </tbody>
    </table>
    </div>
  </div>
</div>
<%= render 'modal_proveedores' %>

app/views/suppliers/update.js.erb
$('#modalProveedores').modal('toggle');
$('#proveedor_<%= @proveedor.id %>').replaceWith(
    '<tr id="proveedor_<%= @proveedor.id %>" ><td><%= @proveedor.nombre %></td><td><%= @proveedor.direccion %></td><td><%= @proveedor.direccion %></td><td><%= link_to 'editar', edit_supplier_path(@proveedor), html_options = {class: "btn btn-info btn-xs", remote: true} %> <%= link_to "Borrar", @proveedor, remote: true, method: :delete, data: { confirm: "¿Borrar proveedor: #{@proveedor.nombre}?"}, class: "btn btn-danger btn-xs" %></td></tr>'
);